apiVersion: batch/v1
kind: CronJob
metadata:
  name: home-crawler
spec:
  schedule: "*/30 * * * *" # 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: producer
            image: aam411/street-crawler:3.0
            imagePullPolicy: IfNotPresent
          restartPolicy: Never