apiVersion: v1
kind: Service
metadata:
  name: http-rest
  labels:
    node-type: es-client
spec:
  type: LoadBalancer
  selector:
    node-type: es-client
  ports:
    - port: 80
      targetPort: 9200
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-client
spec:
  serviceName: es
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: elasticsearch
        node-type: es-client
    spec:
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
        imagePullPolicy: Always
        resources:
            limits:
              cpu: 2
            requests:
              cpu: 1
        ports:
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        - containerPort: 9200
          name: rest
          protocol: TCP
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: node.name
            value: $(HOSTNAME).es.default.svc.cluster.local
          - name: network.host
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: cluster.name
            value: es-cluster-1
          - name: cluster.initial_master_nodes
            value: "es-master-0.es.default.svc.cluster.local"
          - name: discovery.seed_hosts
            value: "es-master-0.es.default.svc.cluster.local" #csv values of every master. ,es-master-1.es.default.svc.cluster.local,es-master-2.es.default.svc.cluster.local
          - name: node.master
            value: "false"
          - name: node.data
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms4G -Xmx4G"