apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-volume
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ec2-user/es/data"